// Regenerate the self-hosted webfonts:  yarn fonts
// Downloads woff2 from Google Fonts (SIL OFL) into public/fonts/ and writes src/fonts.css.
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = process.argv[2] || join(root, 'public/fonts')
const CSS_OUT = process.argv[3] || join(root, 'src/fonts.css')
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

// family spec -> { slug, keepSubsets }
const FAMILIES = [
  { spec: 'Inter:wght@400;500;600', slug: 'inter', keep: ['latin'] },
  { spec: 'Source+Serif+4:wght@600;700', slug: 'source-serif', keep: ['latin'] },
  { spec: 'Noto+Sans+Sinhala:wght@400;500;700', slug: 'noto-sans-sinhala', keep: ['sinhala'] },
  { spec: 'Noto+Serif+Sinhala:wght@600;700', slug: 'noto-serif-sinhala', keep: ['sinhala'] },
]

await mkdir(OUT_DIR, { recursive: true })
let css = `/* Self-hosted fonts — generated by scripts/fetch-fonts (do not edit by hand).\n   Source: Google Fonts (SIL OFL). See .claude/planning/05-i18n.md */\n\n`

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  const sheet = await res.text()

  // split into "/* subset */ @font-face { ... }" chunks
  const blocks = sheet.split('/*').slice(1)
  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim()
    if (!fam.keep.includes(subset)) continue
    const block = raw.slice(raw.indexOf('*/') + 2)

    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400'
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal'
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim()
    const srcUrl = /src:\s*url\(([^)]+)\)/.exec(block)?.[1]
    if (!family || !srcUrl) continue

    const file = `${fam.slug}-${weight}.woff2`
    const bin = Buffer.from(await (await fetch(srcUrl, { headers: { 'User-Agent': UA } })).arrayBuffer())
    await writeFile(join(OUT_DIR, file), bin)
    console.log(`${file}  ${(bin.length / 1024).toFixed(1)} KB  (${subset})`)

    css +=
      `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      (range ? `  unicode-range: ${range};\n` : '') +
      `}\n\n`
  }
}

await writeFile(CSS_OUT, css)
console.log(`\nwrote ${CSS_OUT}`)
